name: Build and Run

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  build-run:
    name: Build, Run and Commit
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build
        run: dotnet build src --configuration Release

      - name: Run the program
        run: |
          echo "${{ secrets.sftp_key }}" > key.pem
          dotnet run --project src/GetMapList --configuration Release -- ${{ secrets.sftp_url }} ${{ secrets.sftp_port }} ${{ secrets.sftp_username }} key.pem

      - name: Check for diff
        id: verify_diff
        shell: bash
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
          
      - name: Commit changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Updated maps.json" -a

      - name: Push changes
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
